### ISSUE TITLE
Crash when installed after starting Atom

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [atom-community/markdown-preview-plus#228]
The package makes my Atom crash every second time I start it. Well not exactly crash, but making all the GUI not work properly and only showing the following error message:

```
Error: Cannot find module '/home/xiaolong/.atom/packages/markdown-preview-plus/createMarkdownPreviewView'
at Module._resolveFilename (module.js:336:15)
at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
at Function.Module._load (module.js:286:25)
at Module.require (module.js:365:17)
at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
at Object.atom.deserializers.add.deserialize [as deserialize] (/usr/share/atom/resources/app.asar/src/package.js:453:41)
at DeserializerManager.module.exports.DeserializerManager.deserialize (/usr/share/atom/resources/app.asar/src/deserializer-manager.js:45:29)
at /usr/share/atom/resources/app.asar/src/pane.js:34:30
at Array.map (native)
at Function.module.exports.Pane.deserialize (/usr/share/atom/resources/app.asar/src/pane.js:33:35)
at DeserializerManager.module.exports.DeserializerManager.deserialize (/usr/share/atom/resources/app.asar/src/deserializer-manager.js:45:29)
at /usr/share/atom/resources/app.asar/src/pane-axis.js:25:30
at Array.map (native)
at Function.module.exports.PaneAxis.deserialize (/usr/share/atom/resources/app.asar/src/pane-axis.js:24:39)
at DeserializerManager.module.exports.DeserializerManager.deserialize (/usr/share/atom/resources/app.asar/src/deserializer-manager.js:45:29)
at PaneContainer.module.exports.PaneContainer.deserialize (/usr/share/atom/resources/app.asar/src/pane-container.js:64:40)
at Workspace.module.exports.Workspace.deserialize (/usr/share/atom/resources/app.asar/src/workspace.js:153:33)
at AtomEnvironment.module.exports.AtomEnvironment.loadStateSync (/usr/share/atom/resources/app.asar/src/atom-environment.js:940:24)
at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom-environment.js:685:12)
at module.exports (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:28:10)
at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:86:5)
at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:41:9)
```

When this message is displayed in the console, I can close Atom and then start it again and the error is gone. But so is the Markdown preview pane. It seems to always happen, when I close Atom having the preview pane visible. Then when it is started again it has some problem with that.

When I get the editor running (every second time) the preview works just fine.

**Comment by lierdakil** [comment]
Sorry about lack of response. Sounds like Atom version is way too old. Closing due to age, feel free to open new issues if this is still a problem on latest Atom/MPP.
