### ISSUE TITLE
Failed to activate the markdown-preview-plus package

### ISSUE THREAD

**Issue by YoKv** [atom-community/markdown-preview-plus#274]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [markdown-preview-plus](https://github.com/Galadirith/markdown-preview-plus) package 2.4.8

### Stack Trace

Failed to activate the markdown-preview-plus package

```
At Cannot find module 'fs-plus'

Error: Cannot find module 'fs-plus'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.14.4/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/markdown-preview-plus-2.4.8/lib/main.coffee:2:6)
    at /packages/markdown-preview-plus-2.4.8/lib/main.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:814:28
```

### Commands

```
```

### Non-Core Packages

```
language-vue 0.21.2 
language-vue-component 0.5.0 
markdown-preview-plus 2.4.8 
```

**Comment by lierdakil** [comment]
Hi. Sorry for the belated reply. This was reported once already in https://github.com/atom-community/markdown-preview-plus/issues/270. I'm not entirely sure what goes wrong, but I would assume un-/reinstalling should generally work. Please let me know if not.

**Comment by lierdakil** [comment]
Closing due to inactivity.

**Comment by xuweicn1** [comment]
The same questions i meet：
1. Install   Node.js
X86 : https://nodejs.org/dist/v4.4.3/node-v4.4.3-x86.msi
X64 : https://nodejs.org/dist/v4.4.3/node-v4.4.3-x64.msi

2. Uninstall Markdown Preview Plus

3. Install Markdown Preview Plus
