### ISSUE TITLE
Error pressing enter

### ISSUE THREAD

**Issue by Thyaris** [atom-community/markdown-preview-plus#285]
[Enter steps to reproduce:]

1. Pressing enter after opening preview and changing linefeeds to unix style

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: 'markdown-writer' package vundefined

### Stack Trace

Uncaught Error: Cannot find module './commands/edit-line'

```
At module.js:457

Error: Cannot find module './commands/edit-line'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.15.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/markdown-writer/lib/markdown-writer.coffee:132:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:19.6.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:19.6.0 autocomplete-plus:confirm (input.hidden-input)
     -0:19.6.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:18.7.0 core:undo (input.hidden-input)
     -0:17.7.0 autocomplete-plus:cancel (input.hidden-input)
  2x -0:17.4.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:10.5.0 editor:consolidate-selections (input.hidden-input)
     -0:10.5.0 core:cancel (input.hidden-input)
     -0:09.8.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:09.3.0 core:backspace (input.hidden-input)
     -0:08.8.0 editor:consolidate-selections (input.hidden-input)
     -0:08.8.0 core:cancel (input.hidden-input)
  3x -0:08.7.0 core:backspace (input.hidden-input)
  4x -0:07.9.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -0:07.0 core:backspace (input.hidden-input)
     -0:06.3.0 markdown-writer:insert-new-line (input.hidden-input)
```

### Non-Core Packages

```
atom-python-run 0.7.3 
git-plus 7.3.3 
language-ini 1.19.0 
language-latex 1.0.0 
language-pgsql 0.2.3 
latex 0.43.0 
markdown-preview-plus 2.4.9 
```

**Comment by lierdakil** [comment]
I'm sorry, but it seems like this error was thrown from `markdown-writer` package, which has little to no relation to MPP.

Furthermore, it seems you uninstalled that package before this error was thrown (It's an educated guess, so I might be off the mark), so I don't think this even counts as a legitimate bug. Probably restarting Atom should fix everything.

Let me know if I'm wrong.

**Comment by lierdakil** [comment]
ETIMEDOUT, closing

**Comment by mauropomar** [comment]
jklklljkljkljkljkljkljkljkl
