### ISSUE TITLE
Uncaught TypeError: this.isReleasedVersion is not a function

### ISSUE THREAD

**Issue by Lxuanx** [atom-community/markdown-preview-plus#289]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [markdown-preview-plus](https://github.com/atom-community/markdown-preview-plus) package 2.4.9

### Stack Trace

Uncaught TypeError: this.isReleasedVersion is not a function

```
At C:\Users\Administrator\AppData\Local\atom\app-1.16.0\resources\app.asar\src\atom-environment.js:990

TypeError: this.isReleasedVersion is not a function
    at /app.asar/src/atom-environment.js:990:17)
    at /app.asar/src/text-editor-element.js:82:12)
    at /app.asar/src/pane-container-element.js:42:14)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at PaneContainer.module.exports.PaneContainer.setRoot (/app.asar/src/pane-container.js:163:20)
    at PaneContainer.module.exports.PaneContainer.replaceChild (/app.asar/src/pane-container.js:173:19)
    at Pane.module.exports.Pane.split (/app.asar/src/pane.js:919:21)
    at Pane.module.exports.Pane.splitRight (/app.asar/src/pane.js:899:19)
    at Pane.module.exports.Pane.findOrCreateRightmostSibling (/app.asar/src/pane.js:971:21)
    at Workspace.open (/app.asar/src/workspace.js:542:39)
    at Object.addPreviewForEditor (/packages/markdown-preview-plus/lib/main.coffee:219:20)
    at Object.toggle (/packages/markdown-preview-plus/lib/main.coffee:194:6)
    at /packages/markdown-preview-plus/lib/main.coffee:144:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -5:50.6.0 core:move-up (input.hidden-input)
     -5:49.6.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -5:49.3.0 markdown-writer:insert-new-line (input.hidden-input)
     -5:49.3.0 editor:newline (input.hidden-input)
  4x -5:39.4.0 core:undo (input.hidden-input)
     -5:37.1.0 find-and-replace:show (input.hidden-input)
     -5:32 core:cancel (button.btn.btn-all)
     -3:43.7.0 core:save (input.hidden-input)
     -3:41.5.0 find-and-replace:show (input.hidden-input)
     -3:36.1.0 core:cancel (button.btn.btn-all)
  6x -3:33 core:save (input.hidden-input)
     -2:36.3.0 find-and-replace:show (input.hidden-input)
     -2:19.2.0 editor:consolidate-selections (input.hidden-input)
     -2:19.2.0 core:cancel (input.hidden-input)
     -0:18.7.0 editor:scroll-to-cursor (input.hidden-input)
     -0:17.5.0 markdown-preview-plus:toggle (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
language-markdown 0.21.0 
markdown-pdf 1.5.0 
markdown-preview-plus 2.4.9 
markdown-scroll-sync 2.1.2 
markdown-writer 2.6.4 
pretty-json 1.6.3 
simplified-chinese-menu 3.5.0 
```

**Comment by lierdakil** [comment]
Thanks for reporting. Pretty sure this is an Atom bug. https://github.com/atom/atom/issues/14138
