### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by changewaver** [atom-community/markdown-preview-plus#294]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [markdown-preview-plus](https://github.com/atom-community/markdown-preview-plus) package 2.4.9

### Stack Trace

Uncaught SyntaxError: Invalid or unexpected token

```
At C:\Users\wayoung\AppData\Local\atom\app-1.17.0\resources\app\src\native-compile-cache.js:97

SyntaxError: Invalid or unexpected token
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.17.0/resources/app/src/native-compile-cache.js:94:1)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.17.0/resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.17.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.17.0/resources/app/src/native-compile-cache.js:66:1)
    at isMarkdownPreviewView (/packages/markdown-preview-plus/lib/main.coffee:9:26)
    at Object.toggle (/packages/markdown-preview-plus/lib/main.coffee:184:8)
    at /packages/markdown-preview-plus/lib/main.coffee:144:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.0/resources/app/src/command-registry.js:265:1)
    at ~/AppData/Local/atom/app-1.17.0/resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.17.0/resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.17.0/resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -0:07.7.0 markdown-preview-plus:toggle (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
atom-beautify 0.29.24 
atom-latex 0.7.8 
convert-to-utf8 0.2.4 
editor-background 1.2.38 
language-latex 1.0.0 
language-markdown 0.22.0 
latex 0.43.0 
markdown-pdf 1.5.0 
markdown-preview-plus 2.4.9 
markdown-writer 2.6.5 
```

**Comment by lierdakil** [comment]
Sorry about lack of response. FWIW, likely compile cache broken, reinstalling usually helps. Shouldn't be an issue with newer versions, since those pretty much vanilla js, as far as Atom is concerned.
