### ISSUE TITLE
Uncaught Error: Unable to watch path

### ISSUE THREAD

**Issue by kuczera** [atom-community/markdown-preview-plus#328]
[Enter steps to reproduce:]

1. Wrting Pandoc-Markdown on Atom
2. Trying to use markdown-preview-plus

**Atom**: 1.23.2 x64
**Electron**: 1.6.15
**OS**: Debian GNU/Linux
**Thrown From**: [markdown-preview-plus](https://github.com/atom-community/markdown-preview-plus) package 2.4.16

### Stack Trace

Uncaught Error: Unable to watch path

```
At /home/kuczera/.atom/packages/markdown-preview-plus/lib/renderer.coffee:94

Error: Unable to watch path
    at HandleWatcher.start (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:95:41)
    at new HandleWatcher (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:28:18)
    at new PathWatcher (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:148:36)
    at Object.exports.watch (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:242:18)
    at Object.getVersion (/packages/markdown-preview-plus/lib/image-watch-helper.coffee:53:32)
    at /packages/markdown-preview-plus/lib/renderer.coffee:115:26
    at resolveImagePaths (/packages/markdown-preview-plus/lib/renderer.coffee:94:31)
    at callbackFunction (/packages/markdown-preview-plus/lib/renderer.coffee:43:12)
    at /packages/markdown-preview-plus/lib/pandoc-helper.coffee:132:5
    at ChildProcess.exithandler (child_process.js:214:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
  2x -2:42.9.0 core:confirm (input.hidden-input)
     -1:45.7.0 application:open-file (input.hidden-input)
     -1:02.6.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:23.4.0 markdown-preview-plus:toggle (input.hidden-input)
```

### Non-Core Packages

```
markdown-footnote 1.1.0 
markdown-preview-plus 2.4.16 
```

**Comment by lierdakil** [comment]
Sorry for the prolonged silence. Long and short of it is, you're probably hitting ulimit on inotify. See, say, https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers for instructions on how to raise this limit.
