### ISSUE TITLE
Uncaught TypeError: event.currentTarget.getModel is not a function

### ISSUE THREAD

**Issue by zorgrian** [atom-community/markdown-preview-plus#340]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.7.11
**OS**: "Manjaro Linux"
**Thrown From**: [markdown-preview-plus](https://github.com/atom-community/markdown-preview-plus) package 2.5.0

### Stack Trace

Uncaught TypeError: event.currentTarget.getModel is not a function

```
At /home/zorg/.atom/packages/markdown-preview-plus/lib/main.js:38

TypeError: event.currentTarget.getModel is not a function
    at HTMLDivElement.close (/packages/markdown-preview-plus/lib/main.js:38:38)
    at CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:388:30)
    at CommandRegistry.dispatch (/usr/lib/atom/src/command-registry.js:273:17)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/lib/atom/src/atom-environment.js:1387:28)
    at EventEmitter.outerCallback (/usr/lib/atom/src/application-delegate.js:321:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```

### Commands

```
     -6:29.1.0 markdown-pdf:convert (input.hidden-input)
     -4:15 core:save (input.hidden-input)
     -3:59.4.0 core:save-as (input.hidden-input)
     -3:44.9.0 markdown-preview:toggle (input.hidden-input)
  3x -3:09.9.0 core:backspace (input.hidden-input)
     -2:33.5.0 core:delete (input.hidden-input)
     -2:24.3.0 intentions:highlight (input.hidden-input)
     -2:23.8.0 core:save (input.hidden-input)
     -1:37.7.0 core:backspace (input.hidden-input)
  2x -1:36 core:move-right (input.hidden-input)
  4x -1:21.1.0 core:move-left (input.hidden-input)
     -1:05.7.0 markdown-writer:insert-new-line (input.hidden-input)
     -1:05.7.0 editor:newline (input.hidden-input)
     -1:04.3.0 markdown-writer:insert-new-line (input.hidden-input)
     -1:04.3.0 editor:newline (input.hidden-input)
     -0:09.4.0 markdown-preview-plus:toggle (div.markdown-preview.has-selection)
```

### Non-Core Packages

```
atom-clock 0.1.16 
busy-signal 1.4.3 
insert-timestamp 0.2.4 
intentions 1.1.5 
language-markdown 0.25.1 
linter 2.2.0 
linter-spell 0.15.0 
linter-ui-default 1.6.10 
markdown-pdf 2.1.0 
markdown-preview-plus 2.5.0 
markdown-scroll-sync 2.1.2 
markdown-writer 2.7.3 
```

**Comment by lierdakil** [comment]
Well, anyway, v2.5.1 released which should disable `markdown-preview` on activation and identifiers used shouldn't intersect with that. Let me know if that resolves the issue.

**Comment by lierdakil** [comment]
ETIMEDOUT
