### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by ZhangC2** [atom-community/markdown-preview-plus#345]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [markdown-preview-plus](https://github.com/atom-community/markdown-preview-plus) package 2.5.1

### Stack Trace

Error: write EPIPE

```
At write EPIPE

Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at Socket._writeGeneric (net.js:715:26)
    at Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at Socket.Writable.write (_stream_writable.js:245:11)
    at Socket.write (net.js:661:40)
    at Promise (/packages/markdown-preview-plus/lib/pandoc-helper.js:123:18)
    at Object.renderPandoc (/packages/markdown-preview-plus/lib/pandoc-helper.js:111:12)
    at render (/packages/markdown-preview-plus/lib/renderer.js:55:29)
    at Object.toDOMFragment (/packages/markdown-preview-plus/lib/renderer.js:13:12)
    at MarkdownPreviewView.renderMarkdownText (/packages/markdown-preview-plus/lib/markdown-preview-view.js:268:25)
    at getMarkdownSource.then (/packages/markdown-preview-plus/lib/markdown-preview-view.js:207:29)
```

### Commands

```
     -0:04.6.0 markdown-preview-plus:toggle (input.hidden-input)
```

### Non-Core Packages

```
markdown-preview-plus 2.5.1 
```

**Comment by lierdakil** [comment]
It would seem Pandoc crashed for some reason. Can't really say anything more without more information on package settings, Pandoc version and what document were you trying to preview.

**Comment by lierdakil** [comment]
ETIMEDOUT, closing.
