### ISSUE TITLE
Support for opening uris like markdown-preview-plus:///path/to/a/file.md

### ISSUE THREAD

**Issue by lexicalunit** [atom-community/markdown-preview-plus#376]
This is supported by `markdown-preview` but seems not to be supported by `markdown-preview-plus` yet.

```
Uncaught (in promise) Error: Tried to open markdown-preview-plus with uri markdown-preview-plus:///Users/me/Dropbox%20(Personal)/nv/TEST.md. This is not supported. Please report this error.
    at opener (/Users/me/.atom/packages/markdown-preview-plus/lib/main.js:207:15)
    at Workspace.createItemForURI (/Applications/Atom Beta.app/Contents/Resources/app/src/workspace.js:1200:28)
    at Workspace.open (/Applications/Atom Beta.app/Contents/Resources/app/src/workspace.js:1010:41)
    at NotesViewList.didConfirmSelection (/Users/me/source/atom/atom-notes/lib/notes-view-list.js:251:22)
    at Object.didConfirmSelection (/Users/me/source/atom/atom-notes/lib/notes-view-list.js:74:41)
    at SelectListView.confirmSelection (/Users/me/source/atom/atom-notes/lib/select-list-view.js:402:20)
    at HTMLDivElement.core:confirm (/Users/me/source/atom/atom-notes/lib/select-list-view.js:98:14)
    at CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:110:40)
opener @ main.ts:281
createItemForURI @ <embedded>:29290
open @ <embedded>:29100
didConfirmSelection @ notes-view-list.js? [sm]:251
didConfirmSelection @ notes-view-list.js? [sm]:74
confirmSelection @ /Users/me/source/atom/atom-notes/lib/select-list-view.js:402
core:confirm @ /Users/me/source/atom/atom-notes/lib/select-list-view.js:98
handleCommandEvent @ <embedded>:23883
module.exports.KeymapManager.dispatchCommandEvent @ <embedded>:69813
module.exports.KeymapManager.handleKeyboardEvent @ <embedded>:69604
handleDocumentKeyEvent @ <embedded>:19511
```

**Comment by lierdakil** [comment]
Could you explain a use case? Thanks.

FWIW, `markdown-preview-plus://`**`file`**`/Users/me/Dropbox%20(Personal)/nv/TEST.md` should work (`file` is literal)

**Comment by lexicalunit** [comment]
I maintain a note taking/searching plugin for Atom. Most users use Markdown for these notes, so it's useful sometimes to be able to browse the notes and have them automatically open in a preview window. For example if you just want to read the note, and not make any change to it.

Otherwise you'd have to 1) open the note, then 2) run the preview command, 3) move the preview tab out of the side panel so you can view if full-width, 4) make sure to keep the note open b/c if you close it the preview closes too, 5) remember to close the note file after you're done looking at the preview.

I'll give it a try with `file` added.

**Comment by lexicalunit** [comment]
🎉 Using `file` worked perfectly!
