### ISSUE TITLE
Failed to activate the markdown-preview-plus package

### ISSUE THREAD

**Issue by ouyxy** [atom-community/markdown-preview-plus#445]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Unknown Windows version
**Thrown From**: [markdown-preview-plus](https://github.com/atom-community/markdown-preview-plus) package 3.7.1

### Stack Trace

Failed to activate the markdown-preview-plus package

```
At Cannot find module 'file-uri-to-path'

Error: Cannot find module 'file-uri-to-path'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.32.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:154368)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:145675)
    at /packages/markdown-preview-plus/lib/markdown-preview-view/webview-handler.js:6:23)
    at /packages/markdown-preview-plus/lib/markdown-preview-view/webview-handler.js:277:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:145675)
    at /packages/markdown-preview-plus/lib/util.js:41:27)
    at /packages/markdown-preview-plus/lib/util.js:78:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:145675)
    at /packages/markdown-preview-plus/lib/markdown-preview-view/util.js:5:16)
    at /packages/markdown-preview-plus/lib/markdown-preview-view/util.js:228:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
```

### Commands

```
```

### Non-Core Packages

```
markdown-preview-plus 3.7.1 
```

**Comment by lierdakil** [comment]
It would seem that the package was broken during installation somehow. This happens from time to time with Atom in general. Most likely some dependencies failed to install (probably due to a faulty Internet connection). Try reinstalling the package (i.e. uninstall then install again).
