### ISSUE TITLE
Failed to load the markdown-preview-plus package

### ISSUE THREAD

**Issue by stat-sky** [atom-community/markdown-preview-plus#447]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.189.0
**System**: linux 4.15.0-43-generic
**Thrown From**: [markdown-preview-plus](https://github.com/atom-community/markdown-preview-plus) package, v3.7.1

### Stack Trace

Failed to load the markdown-preview-plus package

```
At /home/xhy/.atom/packages/markdown-preview-plus/lib/main.js:13
async function activate() {
      ^^^^^^^^
Unexpected token function

/home/xhy/.atom/packages/markdown-preview-plus/lib/main.js:13
async function activate() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:435:25)
    at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:678:34)
    at /usr/share/atom/resources/app/src/package.js:189:28
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app/src/package.js:181:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app/src/package-manager.js:383:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:460:30)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:268:29
    at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
    at BufferedProcess.triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:63:47)
    at /usr/share/atom/resources/app/src/buffered-process.js:77:18
    at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:150:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:166:7)
    at Pipe.close (net.js:464:12)

```

### Commands

```
     -6:18.4 settings-view:install-packages-and-themes (atom-pane.pane.active)
     -5:19.8 core:paste (atom-text-editor.editor.mini)
     -5:17.3 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-simplified-chinese-menu, v0.6.5
markdown-preview-plus, v3.7.1

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Your Atom version is *ancient*, it's pre-v1.0 -- which is to say, it's almost 4 years old at this point. Please install an up-to-date Atom version. The latest released Atom version at the time of writing is v1.34.0
