### ISSUE TITLE
Uncaught error TypeError in markdown-preview-plus webview client

### ISSUE THREAD

**Issue by Isaac343** [atom-community/markdown-preview-plus#448]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Ubuntu 18.04.1
**Thrown From**: [markdown-preview-plus](https://github.com/atom-community/markdown-preview-plus) package 3.7.1

### Stack Trace

Uncaught error TypeError in markdown-preview-plus webview client

```
At Cannot read property '0' of undefined

stack:
TypeError: Cannot read property '0' of undefined
    at file:///home/isaac/.atom/packages/markdown-preview-plus/node_modules/mathjax/jax/output/SVG/fonts/TeX/fontdata.js?V=2.7.4:19:142461
    at Function.execute (file:///home/isaac/.atom/packages/markdown-preview-plus/node_modules/mathjax/MathJax.js?delayStartupUntil=configured:19:3242)
    at cb (file:///home/isaac/.atom/packages/markdown-preview-plus/node_modules/mathjax/MathJax.js?delayStartupUntil=configured:19:2819)
    at Object.Execute (file:///home/isaac/.atom/packages/markdown-preview-plus/node_modules/mathjax/MathJax.js?delayStartupUntil=configured:19:7455)
    at Object.loadComplete (file:///home/isaac/.atom/packages/markdown-preview-plus/node_modules/mathjax/MathJax.js?delayStartupUntil=configured:19:16244)
    at Object.loadTimeout (file:///home/isaac/.atom/packages/markdown-preview-plus/node_modules/mathjax/MathJax.js?delayStartupUntil=configured:19:16417)
    at Function.execute (file:///home/isaac/.atom/packages/markdown-preview-plus/node_modules/mathjax/MathJax.js?delayStartupUntil=configured:19:3242)
    at HTMLScriptElement.cb (file:///home/isaac/.atom/packages/markdown-preview-plus/node_modules/mathjax/MathJax.js?delayStartupUntil=configured:19:2819)


Error
    at HTMLElement.WebviewHandler._element.addEventListener (/packages/markdown-preview-plus/lib/markdown-preview-view/webview-handler.js:37:36)
    at WebViewImpl.dispatchEvent (/usr/share/atom/resources/electron.asar/renderer/web-view/web-view.js:177:22)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/electron.asar/renderer/web-view/guest-view-internal.js:79:15)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-updater-linux 1.3.0 
color-picker 2.3.0 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
file-icons 2.1.28 
ide-php 0.7.18 
ide-python 1.2.0 
language-x86asm 0.9.0 
markdown-preview-plus 3.7.1 
minimap 4.29.9 
platformio-ide-terminal 2.8.4 
script 3.18.1 
teletype 0.13.3 
```

**Comment by lierdakil** [comment]
Sorry, but I need more information to help with this. All I can say right now is that apparently MathJax fails to do something with fonts here. Could you write a reproduction guide?
