### ISSUE TITLE
Uncaught error SyntaxError in markdown-preview-plus webview client

### ISSUE THREAD

**Issue by good1uck** [atom-community/markdown-preview-plus#452]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [markdown-preview-plus](https://github.com/atom-community/markdown-preview-plus) package 3.8.0

### Stack Trace

Uncaught error SyntaxError in markdown-preview-plus webview client

```
At Failed to execute 'querySelector' on 'Document': '#%E5%9F%B9%E8%AE%AD' is not a valid selector.

stack:
Error: Failed to execute 'querySelector' on 'Document': '#%E5%9F%B9%E8%AE%AD' is not a valid selector.
    at HTMLDocument.<anonymous> (file:///C:/Users/dev/.atom/packages/markdown-preview-plus/client/main.c39d6dcf.js:10:7359)

Error
    at HTMLElement.WebviewHandler._element.addEventListener (/packages/markdown-preview-plus/lib/markdown-preview-view/webview-handler.js:36:36)
    at WebViewImpl.dispatchEvent (~/AppData/Local/atom/app-1.35.1/resources/electron.asar/renderer/web-view/web-view.js:177:22)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.35.1/resources/electron.asar/renderer/web-view/guest-view-internal.js:79:15)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -7:18.9.0 core:copy (input.hidden-input)
     -3:58.2.0 command-palette:toggle (input.hidden-input)
     -3:55.5.0 core:confirm (input.hidden-input)
  2x -3:55.5.0 markdown-toc:update (input.hidden-input)
     -3:47.8.0 core:select-all (input.hidden-input)
     -3:47.3.0 core:copy (input.hidden-input)
     -0:24.5.0 command-palette:toggle (input.hidden-input)
     -0:23 core:move-down (input.hidden-input)
     -0:22.7.0 core:confirm (input.hidden-input)
     -0:22.7.0 markdown-toc:delete (input.hidden-input)
     -0:14.6.0 command-palette:toggle (input.hidden-input)
  2x -0:11.6.0 core:move-down (input.hidden-input)
     -0:09.7.0 core:move-up (input.hidden-input)
     -0:09.3.0 core:move-down (input.hidden-input)
     -0:09.1.0 core:confirm (input.hidden-input)
     -0:09.1.0 markdown-toc:create (input.hidden-input)
```

### Non-Core Packages

```
language-markdown 0.29.0 
markdown-preview-plus 3.8.0 
markdown-toc 0.4.2 
```

**Comment by lierdakil** [comment]
Thanks for reporting! Should be fixed in v3.8.1
