### ISSUE TITLE
Uncaught error InvalidCharacterError in markdown-preview-plus webview client

### ISSUE THREAD

**Issue by mx-projects** [atom-community/markdown-preview-plus#470]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Unknown Windows version
**Thrown From**: [markdown-preview-plus](https://github.com/atom-community/markdown-preview-plus) package 3.11.0

### Stack Trace

Uncaught error InvalidCharacterError in markdown-preview-plus webview client

```
At Failed to execute 'setAttribute' on 'Element': '<h2' is not a valid attribute name.

stack:
Error: Failed to execute 'setAttribute' on 'Element': '<h2' is not a valid attribute name.
    at morphAttrs (C:\Users\root\.atom\packages\markdown-preview-plus\node_modules\morphdom\dist\morphdom.js:32:26)
    at morphEl (C:\Users\root\.atom\packages\markdown-preview-plus\node_modules\morphdom\dist\morphdom.js:476:17)
    at morphChildren (C:\Users\root\.atom\packages\markdown-preview-plus\node_modules\morphdom\dist\morphdom.js:584:33)
    at morphEl (C:\Users\root\.atom\packages\markdown-preview-plus\node_modules\morphdom\dist\morphdom.js:486:15)
    at morphdom (C:\Users\root\.atom\packages\markdown-preview-plus\node_modules\morphdom\dist\morphdom.js:701:13)
    at n.<anonymous> (file:///C:/Users/root/.atom/packages/markdown-preview-plus/client/main.c39d6dcf.js:2:2050)
    at file:///C:/Users/root/.atom/packages/markdown-preview-plus/client/main.c39d6dcf.js:2:1301
    at Object.next (file:///C:/Users/root/.atom/packages/markdown-preview-plus/client/main.c39d6dcf.js:2:1406)
    at file:///C:/Users/root/.atom/packages/markdown-preview-plus/client/main.c39d6dcf.js:2:319
    at new Promise (<anonymous>)

Error
    at HTMLElement.WebviewHandler._element.addEventListener (/packages/markdown-preview-plus/lib/markdown-preview-view/webview-handler.js:36:36)
    at WebViewImpl.dispatchEvent (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/renderer/web-view/web-view.js:142:22)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/renderer/web-view/guest-view-internal.js:81:15)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
     -1:02.9.0 core:move-left (input.hidden-input)
  7x -1:02.3.0 core:move-down (input.hidden-input)
  2x -1:00.7.0 core:move-right (input.hidden-input)
     -1:00.0 core:move-down (input.hidden-input)
  3x -0:59.7.0 core:move-up (input.hidden-input)
     -0:58.8.0 editor:move-to-end-of-screen-line (input.hidden-input)
  3x -0:53.3.0 core:backspace (input.hidden-input)
  7x -0:50.9.0 core:move-up (input.hidden-input)
  3x -0:49.4.0 core:move-left (input.hidden-input)
  5x -0:48.5.0 core:move-down (input.hidden-input)
     -0:47.7.0 core:move-left (input.hidden-input)
     -0:19.5.0 snippets:next-tab-stop (input.hidden-input)
     -0:19.5.0 snippets:expand (input.hidden-input)
     -0:19.5.0 editor:indent (input.hidden-input)
     -0:18.8.0 editor:newline (input.hidden-input)
     -0:15.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
asciidoc-preview 2.13.1 
atom-beautify 0.33.4 
atom-file-icons 0.7.1 
atom-ternjs 0.20.0 
emmet 2.4.3 
highlight-selected 0.16.0 
language-asciidoc 1.11.0 
language-vue 0.25.0 
markdown-preview-plus 3.11.0 
markdown-themeable-pdf 1.2.1 
pdf-view 0.72.0 
Zen 0.18.0 
```

**Comment by lierdakil** [comment]
Hi. Sorry for the prolonged silence.

I honestly have no idea how to reproduce this. If you could describe how you got this error, that would dramatically increase the chance of it being fixed.

**Comment by mx-projects** [comment]
Sorry, I can't remember exactly what happened.I seem to have updated some of the plugins, then something went wrong and I hit the submit button.

**Comment by mx-projects** [comment]
markdown-preview-plus 3.11.0 and emmet 2.4.3 have Have the same Keybindings.Not sure if that's the reason.

**Comment by lierdakil** [comment]
Probably not.
