### ISSUE TITLE
Error reported when Markdown Preview Plus view is loading

### ISSUE THREAD

**Issue by fefedelcid** [atom-community/markdown-preview-plus#483]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Windows 10 Pro
**Thrown From**: [markdown-preview-plus](https://github.com/atom-community/markdown-preview-plus) package 3.11.5

### Stack Trace

Error reported when Markdown Preview Plus view is loading

```
At Cannot find module 'uc.micro/categories/Cc/regex'

Error: Cannot find module 'uc.micro/categories/Cc/regex'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.45.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (<embedded>:11:146745)
    at module.exports (/packages/markdown-preview-plus/node_modules/linkify-it/lib/re.js:9:16)
    at compile (/packages/markdown-preview-plus/node_modules/linkify-it/index.js:153:41)
    at /packages/markdown-preview-plus/node_modules/linkify-it/index.js:395:3)
    at /packages/markdown-preview-plus/node_modules/markdown-it/lib/index.js:290:18)
    at MarkdownIt (/packages/markdown-preview-plus/node_modules/markdown-it/lib/index.js:223:12)
    at init (/packages/markdown-preview-plus/lib/markdown-it-helper.js:71:24)
    at /packages/markdown-preview-plus/lib/markdown-it-helper.js:120:26
    at Object.render (/packages/markdown-preview-plus/lib/markdown-it-helper.js:127:24)
    at Object.render (/packages/markdown-preview-plus/lib/renderer.js:29:27)
    at MarkdownPreviewViewEditor.renderMarkdownText (/packages/markdown-preview-plus/lib/markdown-preview-view/markdown-preview-view.js:205:48)
    at MarkdownPreviewViewEditor.renderMarkdown (/packages/markdown-preview-plus/lib/markdown-preview-view/markdown-preview-view.js:190:21)

```

### Commands

```
     -9:57.3.0 markdown-writer:insert-new-line (input.hidden-input)
     -9:57.3.0 editor:newline (input.hidden-input)
     -9:50.2.0 markdown-preview:toggle (input.hidden-input)
  7x -8:02.0 core:backspace (input.hidden-input)
     -7:55.9.0 core:confirm (input.hidden-input)
     -6:01.0 core:backspace (input.hidden-input)
     -2:47.3.0 core:delete (input.hidden-input)
     -1:54 core:paste (input.hidden-input)
     -0:24.6.0 markdown-preview-plus:toggle (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.16.0 
file-icons 2.1.39 
Hydrogen 2.14.1 
ide-json 0.2.1 
kite 0.180.0 
language-markdown 0.37.0 
markdown-helper 0.3.0 
markdown-preview-plus 3.11.5 
pp 0.0.1 
processing 0.13.0 
processing-autocomplete 0.2.0 
processing-language 0.2.0 
script 3.25.0 
tool-bar-markdown 1.0.5 
```

**Comment by lierdakil** [comment]
It seems some module files are missing or corrupted. Could you try removing and reinstalling the package to see if that helps?

**Comment by lierdakil** [comment]
Alternatively, you might try opening the package install directory (which is located in atom home directory) in the terminal and running `apm install` there (which should hopefully fix any missing/corrupted dependencies)

**Comment by Merovex** [comment]
I just installed this fresh on a (reasonably) fresh Atom instance on Win10. It ran initially, then I tinkered with the configurations and it failed. The error message led me here.

I had switched from Markdown-IT to Pandoc, and the system did not have Pandoc installed. So, I installed Pandoc, then reloaded Atom. That fixed it in my case.

**Comment by lierdakil** [comment]
@Merovex, the error message in the OP reports `'uc.micro/categories/Cc/regex'` module missing. That should've been installed during the package installation, hence the reinstallation recommendation.

The missing pandoc executable error should be pretty different when looking at the details.

Atom can sometimes be pretty misleading when linking issues, regrettably.

**Comment by lierdakil** [comment]
Issues of this type largely shouldn't happen now that almost all dependencies are bundled with the package.
