### ISSUE TITLE
Failed to activate the markdown-preview-plus package

### ISSUE THREAD

**Issue by H1207953831** [atom-community/markdown-preview-plus#485]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [markdown-preview-plus](https://github.com/atom-community/markdown-preview-plus) package 3.11.5

### Stack Trace

Failed to activate the markdown-preview-plus package

```
At Cannot find module 'file-uri-to-path'

Error: Cannot find module 'file-uri-to-path'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.45.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:146745)
    at /packages/markdown-preview-plus/lib/markdown-preview-view/webview-handler.js:5:23)
    at /packages/markdown-preview-plus/lib/markdown-preview-view/webview-handler.js:205:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:146745)
    at /packages/markdown-preview-plus/lib/util.js:41:27)
    at /packages/markdown-preview-plus/lib/util.js:85:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:146745)
    at /packages/markdown-preview-plus/lib/markdown-preview-view/util.js:5:16)
    at /packages/markdown-preview-plus/lib/markdown-preview-view/util.js:207:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
```

### Commands

```
```

### Non-Core Packages

```
atom-markdown-auto-preview 1.1.1 
simplified-chinese-menu 5.3.5 
markdown-preview-plus 3.11.5 
```

**Comment by lierdakil** [comment]
Looks like one of the dependencies failed to install. Try uninstalling and re-installing the package.

**Comment by lierdakil** [comment]
Alternatively, find the package directory and run `apm install` there, which should hopefully pull in any missing dependencies.

**Comment by lierdakil** [comment]
This kind of error shouldn't happen post v4.0.0 since dependencies are bundled now.
