### ISSUE TITLE
Uncaught TypeError: this._element.print is not a function

### ISSUE THREAD

**Issue by Bharath-RoyChoudhury** [atom-community/markdown-preview-plus#488]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.4
**Thrown From**: [markdown-preview-plus](https://github.com/atom-community/markdown-preview-plus) package 3.11.5

### Stack Trace

Uncaught TypeError: this._element.print is not a function

```
At /Users/broychou/.atom/packages/markdown-preview-plus/lib/markdown-preview-view/webview-handler.js:155

TypeError: this._element.print is not a function
    at WebviewHandler.print (/packages/markdown-preview-plus/lib/markdown-preview-view/webview-handler.js:155:23)
    at /packages/markdown-preview-plus/lib/markdown-preview-view/markdown-preview-view.js:154:30)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349576)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:348051)
    at AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:726039)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:734045)
    at EventEmitter.emit (events.js:194:13)
```

### Commands

```
     -5:40.8.0 markdown-preview-plus:toggle (input.hidden-input)
     -5:15.5.0 core:backspace (input.hidden-input)
  2x -4:32.7.0 markdown-preview-plus:toggle (input.hidden-input)
     -2:27.6.0 markdown-preview-enhanced:toggle (input.hidden-input)
  2x -1:40.4.0 core:save-as (webview.markdown-preview-plus.native-key-bindings)
     -0:59.7.0 markdown-preview-plus:new-window (webview.markdown-preview-plus.native-key-bindings)
     -0:50.7.0 markdown-preview-enhanced:toggle (input.hidden-input)
     -0:28.1.0 markdown-preview-plus:toggle (input.hidden-input)
     -0:20.3.0 markdown-preview-enhanced:sync-preview (ul.list-inline.tab-bar.inset-panel)
     -0:10.1.0 markdown-preview-plus:print (webview.markdown-preview-plus.native-key-bindings)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
autocomplete-latex-cite 0.3.5 
autocomplete-latex-references 0.3.2 
busy-signal 2.0.1 
intentions 1.1.5 
language-latex 1.2.0 
language-markdown 0.37.0 
latex 0.50.2 
latex-autocomplete 1.1.1 
latex-hyperclick 0.2.0 
latex-wordcount 0.6.0 
linter 2.3.1 
linter-chktex 1.4.0 
linter-spell-latex 0.11.0 
linter-ui-default 1.8.1 
markdown-preview-enhanced 0.18.1 
markdown-preview-plus 3.11.5 
pdf-view 0.72.0 
```

**Comment by lierdakil** [comment]
Upstream broke some things in v1.47.0, the only workaround at the moment is to downgrade to v1.46.0. See https://github.com/atom-community/markdown-preview-plus/issues/487
