### ISSUE TITLE
Error reported when Markdown Preview Plus view is loading

### ISSUE THREAD

**Issue by Jerryyuanyuan** [atom-community/markdown-preview-plus#508]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Ubuntu 18.04.5
**Thrown From**: [markdown-preview-plus](https://github.com/atom-community/markdown-preview-plus) package 4.7.0

### Stack Trace

Error reported when Markdown Preview Plus view is loading

```
At Invalid Point: (NaN, 0)

TypeError: Invalid Point: (NaN, 0)
    at Function.Point.assertValid (/usr/share/atom/resources/app/static/<embedded>:14:49995)
    at DisplayLayer.translateScreenPosition (/usr/share/atom/resources/app/static/<embedded>:14:91101)
    at TextEditor.bufferRowForScreenRow (/usr/share/atom/resources/app/static/<embedded>:11:13958)
    at co.getScrollSyncParams (/packages/markdown-preview-plus/dist/main.js:1:209200)
    at _o.renderMarkdownText (/packages/markdown-preview-plus/dist/main.js:1:221826)
```

### Commands

```
```

### Non-Core Packages

```
language-markdown 0.37.0 
markdown-image-paste 2.5.2 
markdown-img-paste 0.4.0 
markdown-preview-plus 4.7.0 
markdown-table-editor 1.1.2 
markdown-themeable-pdf 1.2.1 
pdf-view 0.72.0 
```

**Comment by rjbergerud** [comment]
Any reason why this issue was closed?  I'm having the same 

[Enter steps to reproduce:]

1. Update to 4.10.0
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.4
**Thrown From**: [markdown-preview-plus](https://github.com/atom-community/markdown-preview-plus) package 4.10.0


### Stack Trace

Error reported when Markdown Preview Plus view is loading

```
At write EPIPE

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:149:25)
    at writeGeneric (internal/stream_base_commons.js:140:3)
    at Socket._writeGeneric (net.js:776:11)
    at Socket._write (net.js:788:8)
    at doWrite (_stream_writable.js:435:12)
    at writeOrBuffer (_stream_writable.js:419:5)
    at Socket.Writable.write (_stream_writable.js:309:11)
    at /packages/markdown-preview-plus/dist/main.js:1:77939
    at new Promise (<anonymous>)
    at /packages/markdown-preview-plus/dist/main.js:1:77546)
    at /packages/markdown-preview-plus/dist/main.js:1:75833)
    at Ao.renderMarkdownText (/packages/markdown-preview-plus/dist/main.js:1:224277)
    at Ao.renderMarkdown (/packages/markdown-preview-plus/dist/main.js:1:223970)
```

### Commands

```
     -1:17.8.0 editor:consolidate-selections (input.hidden-input)
     -1:17.8.0 core:cancel (input.hidden-input)
     -1:16.8.0 core:select-up (input.hidden-input)
  4x -1:15.6.0 emmet:merge-lines (input.hidden-input)
  2x -1:10.4.0 core:move-left (input.hidden-input)
  3x -1:09.7.0 datatip:toggle (input.hidden-input)
     -1:07.3.0 core:backspace (input.hidden-input)
     -1:05.3.0 command-palette:toggle (input.hidden-input)
     -1:00.1.0 editor:consolidate-selections (input.hidden-input)
     -1:00.1.0 core:cancel (input.hidden-input)
     -0:58.9.0 emmet:merge-lines (input.hidden-input)
     -0:57.6.0 application:add-project-folder (input.hidden-input)
     -0:54.2.0 command-palette:toggle (input.hidden-input)
     -0:51.9.0 core:move-down (input.hidden-input)
     -0:51.4.0 core:confirm (input.hidden-input)
     -0:51.4.0 markdown-preview-plus:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-debugger-python 0.7.3 
atom-ide-ui 0.13.0 
atom-language-r 1.4.8 
atom-live-server 2.3.0 
atom-ternjs 0.20.0 
autocomplete 0.47.0 
autocomplete-python 1.17.0 
autocomplete-sql 0.5.0 
busy-signal 2.0.1 
dash 1.7.1 
emmet 2.4.3 
git-blame 1.8.0 
git-time-machine 2.1.0 
go-debug 1.7.0 
go-plus 6.1.0 
go-signature-statusbar 1.2.3 
goto-definition 1.3.4 
Hydrogen 2.15.3 
hydrogen-launcher 1.2.2 
hydrogen-python 0.0.8 
ide-html 0.6.2 
ide-python 1.8.0 
ide-r 0.1.8 
ide-svelte 0.1.1 
indent-detective 0.4.0 
ink 0.12.6 
julia-client 0.12.6 
kite 0.197.0 
language-aadl 0.1.0 
language-julia 0.21.1 
language-latex 1.2.0 
language-matlab 0.2.1 
language-tex 0.4.0 
latex 0.50.2 
latex-completions 0.3.6 
linter 3.1.1 
linter-flake8 2.4.0 
markdown-pdf 2.3.3 
markdown-preview-plus 4.10.0 
pdf-view 0.72.0 
pen-paper-coffee-syntax 0.17.0 
pg-formatter 0.0.1 
prettier-atom 0.60.1 
python-debugger 0.2.0 
python-docstring 0.0.3 
react 0.18.0 
split-diff 1.4.0 
sync-settings 5.2.11 
tablr 1.8.3 
tikz-preview 0.2.8 
tool-bar 1.4.2 
uber-juno 0.3.0 
```

**Comment by rjbergerud** [comment]
nvmnd!  Didn't have pandoc.

**Comment by Bambunote** [comment]
You can open another. I have met the same problem.

**Comment by ms609** [comment]
I hit this error when pandoc wasn't found – and resolved it by specifying "Path to Pandoc executable".

I wonder whether it's possible for the UI to return a more informative error message natively when pandoc is not found?
