### ISSUE TITLE
Uncaught TypeError: t.getWebContentsId is not a function

### ISSUE THREAD

**Issue by zaw-shinoto** [atom-community/markdown-preview-plus#521]
I opened a markdown file with extension .md from a Seafile sync library and got this message. 

**Atom**: 1.50.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.7
**Thrown From**: [markdown-preview-plus](https://github.com/atom-community/markdown-preview-plus) package 4.9.1

### Stack Trace

Uncaught TypeError: t.getWebContentsId is not a function

```
At /Users/.../.atom/packages/markdown-preview-plus/dist/main.js:1

TypeError: t.getWebContentsId is not a function
    at HTMLElement.n (/packages/markdown-preview-plus/dist/main.js:1:91917)
    at WebViewImpl.dispatchEvent (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/web-view-impl.js:125:22)
    at dispatchEvent (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/guest-view-internal.js:56:11)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/guest-view-internal.js:74:7)
    at EventEmitter.emit (events.js:194:13)
```

### Commands

```
     -0:09.0 markdown-preview-plus:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-focus-mode 1.0.0 
atom-html-preview 0.2.6 
atom-material-syntax 1.0.8 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.1.3 
busy-signal 2.0.1 
custom-folds 1.9.5 
document-outline 2.1.2 
emmet 2.4.3 
git-control 0.9.0 
git-history 3.3.0 
git-log 0.4.1 
git-plus 8.7.1 
git-time-machine 2.1.0 
github-atom-light-syntax 0.5.0 
highlight-line 0.12.0 
highlight-selected 0.17.0 
html-tag-auto-complete 2.1.0 
hugofy 2.0.0 
intentions 1.1.5 
language-hugo 0.5.1 
language-markdown 0.37.0 
line-length-break 0.4.0 
linter 3.3.0 
linter-chktex 1.4.0 
linter-csslint 2.0.6 
linter-sass-lint 1.9.0 
linter-ui-default 3.0.2 
markdown-fold 0.3.0 
markdown-pdf 2.3.3 
markdown-preview-plus 4.9.1 
markdown-table-editor 1.1.3 
markdown-table-formatter 2.9.2 
markdown-themeable-pdf 1.2.1 
markdown-writer 2.11.11 
minimap 4.39.10 
minimap-bookmarks 0.4.6 
minimap-highlight-selected 4.6.5 
minimap-pigments 0.2.2 
naturezen-light-syntax 0.1.0 
open-recent 5.0.0 
pandoc-convert 1.1.1 
pdf-view 0.72.0 
pigments 0.40.6 
sort-lines 0.19.0 
split-diff 1.6.1 
tasks 2.10.1 
todo-show 2.3.2 
tool-bar 1.4.2 
tool-bar-markdown-writer 0.5.1 
tree-view-git-status 1.5.3 
typewriter 0.8.0 
wordcount 3.2.0 
Zen 0.18.0 
```

**Comment by lierdakil** [comment]
Please update to Atom v1.55.0.

**Comment by zaw-shinoto** [comment]
Thanks for the quick response, that got it working.
